SELECT DISTINCT ?name ?country ?rating
WHERE
 { 	?x <http://dbpedia.org/ontology/name> ?name;
	   <http://dbpedia.org/ontology/country> ?country;
	   <http://dbpedia.org/ontology/rating> ?rating.
}
ORDER BY DESC(?rating)
LIMIT 10
